CREATE DATABASE VENDAS;

CREATE TABLE PRODUTO (
    ID BIGSERIAL NOT NULL PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    DESCRICAO VARCHAR(255),
    PRECO NUMERIC(16, 2),
    SKU VARCHAR(20),
    DATA_CADASTRO DATE
);

CREATE TABLE CLIENTE (
    ID BIGSERIAL NOT NULL PRIMARY KEY,
    NASCIMENTO DATE NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    ENDERECO VARCHAR(255) NOT NULL,
    CPF VARCHAR(14) NOT NULL,
    TELEFONE VARCHAR(14),
    EMAIL VARCHAR(100),
    DATA_CADASTRO DATE
);
